---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: workstations
  become: true
  tasks:


- hosts: web_servers
  become: true
  tasks:

  - name: Install unzip
    package:
      name: unzip

  - name: Install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Install Apache and PHP packages
    tags: apache,centos,httpd
    yum: 
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Start httpd (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644