---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache and PHP packages
    tags: apache,centos,httpd
    yum: 
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Start httpd (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644