---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache and PHP packages
    yum: 
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
